name: Kubsh CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deb:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make libfuse3-dev pkg-config
          
      - name: Build deb package
        run: |
          make clean
          make deb
          
      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb
          path: kubsh.deb
          retention-days: 1

  run-tests:
    runs-on: ubuntu-22.04
    needs: build-deb  # Явная зависимость
    steps:
      - uses: actions/checkout@v4
      
      - name: Download deb artifact
        uses: actions/download-artifact@v4
        with:
          name: kubsh-deb
          path: /tmp
      
      - name: Setup environment and run tests
        run: |
          # Установка зависимостей
          sudo apt-get update
          sudo apt-get install -y build-essential g++ make libfuse3-dev pkg-config fuse3
          
          # Установка пакета
          sudo apt install -y /tmp/kubsh.deb
          
          # Запуск тестов в контейнере с FUSE
          docker run --rm --privileged -v /dev/fuse:/dev/fuse -v /tmp:/mnt tyvik/kubsh_test:master /opt/check.sh
